---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure sudorule is present with the given order.
  - ipasudorule:
      ipaadmin_password: MyPassword123
      name: testrule1
      runasuser: admin
      action: member
      state: absent
